### ISSUE TITLE
error <my_config.h> MUST be included first - CentOS 7

### ISSUE THREAD

**Issue by danpilch** [farcepest/MySQLdb1#89] opened 2014-11-19 14:52 UTC
Hi,

The newest version of mariadb-devel (mariadb-devel-5.5.40-1.el7_0.x86_64) on CentOS 7 breaks when installing MySQL-python via pip:

In file included from /usr/include/mysql/my_config.h:14:0,

```
             from _mysql.c:44:
```

/usr/include/mysql/my_config_x86_64.h:654:2: error: #error <my_config.h> MUST be included first!

 #error <my_config.h> MUST be included first!

  ^

error: command 'gcc' failed with exit status 1

I resolved this by removing all mariadb packages via yum:

yum remove maria*

Then installing an older version (mariadb-devel-5.5.37-1.el7_0.x86_64). This seemed to fix the issue.

Hope this can help anyone else in the same situation.

**Comment by methane** [comment] 2014-11-19 16:25
FYI, [mysqlclient](https://pypi.python.org/pypi/mysqlclient) has fixed it.
https://github.com/PyMySQL/mysqlclient-python/pull/7

**Comment by rbu** [comment] 2014-11-21 10:45
Duplicate of #80

**Closed as completed** 2016-09-18 14:27 UTC
